version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    volumes:
      - ../src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - ../src:/var/www/html

  db:
    image: mysql:latest
    container_name: db-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  db_data:
